package com.qorpy.api.enums;

public enum AuditActionType {
    LOGIN, LOGOUT,
    LOGIN_FAILED,
    ACCOUNT_CREATED, ACCOUNT_EDITED, ACCOUNT_DEACTIVATED,
    TAXPAYER_SUSPENDED, TAXPAYER_REINSTATED, TAXPAYER_ANNOTATED,
    TAXPAYER_FLAGGED, ALERT_CONFIGURED, ALERT_DEACTIVATED
}
